// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Url struct {
	ID        int64
	Code      string
	LongUrl   string
	CreatedAt pgtype.Timestamptz
}
