// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Url struct {
	ID        int64
	LongUrl   string
	Clicks    int32
	CreatedAt pgtype.Timestamptz
	UserID    pgtype.Int8
}

type User struct {
	ID           int32
	Email        string
	PasswordHash string
	CreatedAt    pgtype.Timestamp
}
