// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package sqlc

import (
	"context"
)

const createShortURL = `-- name: CreateShortURL :one
INSERT INTO urls (long_url)
VALUES ($1)
RETURNING id, long_url, clicks, created_at
`

func (q *Queries) CreateShortURL(ctx context.Context, longUrl string) (Url, error) {
	row := q.db.QueryRow(ctx, createShortURL, longUrl)
	var i Url
	err := row.Scan(
		&i.ID,
		&i.LongUrl,
		&i.Clicks,
		&i.CreatedAt,
	)
	return i, err
}

const getLongURL = `-- name: GetLongURL :one
SELECT id, long_url, clicks, created_at FROM urls
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetLongURL(ctx context.Context, id int64) (Url, error) {
	row := q.db.QueryRow(ctx, getLongURL, id)
	var i Url
	err := row.Scan(
		&i.ID,
		&i.LongUrl,
		&i.Clicks,
		&i.CreatedAt,
	)
	return i, err
}
